project:
  type: "website"
  title: "mysite"
  output-dir: docs
  render:
    - "*.qmd"
    - "!code/"
    - "!data/"
    - "!output"
    

website:
  title: "mysite"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: analysis/index.qmd
        text: Analysis
      - about.qmd
    logo: assets/logo.png
    background: "dark"
    search: true
      # - menu:
      #   - href: analysis/analysis1.qmd
      #     text: analysis
  # open-graph: true
  # twitter-card: 
  #   title: twitter
  #   site: "@chaodai"
  # comments: 
  #   hypothesis:
  #     theme: classic
  #     openSidebar: false
format:
  html:
    theme: sandstone
    css: styles.css
